In [1]:
ls

drive/  sample_data/

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

After mounting, you can load your dataset using a library like pandas. Make sure to replace the placeholder path with the actual path to your file in Google Drive.

In [6]:
import pandas as pd
import numpy as np
import random
from datetime import datetime, timedelta
import plotly.express as px
print('Done')

# Replace 'your_dataset_name.csv' with the actual name of your file
# You can find the path by navigating your Drive in the Colab file browser
file_path = '/content/drive/MyDrive/Health_AnimalBites.csv'

try:
    df = pd.read_csv(file_path)
    print("Dataset loaded successfully!")
    display(df.head())
except FileNotFoundError:
    print(f"Error: The file '{file_path}' was not found. Please check the path and filename.")
except Exception as e:
    print(f"An error occurred while loading the dataset: {e}")

Done
Dataset loaded successfully!

,bite_date,SpeciesIDDesc,BreedIDDesc,GenderIDDesc,color,vaccination_yrs,vaccination_date,victim_zip,AdvIssuedYNDesc,WhereBittenIDDesc,quarantine_date,DispositionIDDesc,head_sent_date,release_date,ResultsIDDesc
0,1985-05-05 00:00:00,DOG,NaN,FEMALE,LIG. BROWN,1.0,1985-06-20 00:00:00,40229,NO,BODY,1985-05-05 00:00:00,UNKNOWN,NaN,NaN,UNKNOWN
1,1986-02-12 00:00:00,DOG,NaN,UNKNOWN,BRO & BLA,NaN,NaN,40218,NO,BODY,1986-02-12 00:00:00,UNKNOWN,NaN,NaN,UNKNOWN
2,1987-05-07 00:00:00,DOG,NaN,UNKNOWN,NaN,NaN,NaN,40219,NO,BODY,1990-05-07 00:00:00,UNKNOWN,NaN,NaN,UNKNOWN
3,1988-10-02 00:00:00,DOG,NaN,MALE,BLA & BRO,NaN,NaN,NaN,NO,BODY,1990-10-02 00:00:00,UNKNOWN,NaN,NaN,UNKNOWN
4,1989-08-29 00:00:00,DOG,NaN,FEMALE,BLK-WHT,NaN,NaN,NaN,NO,BODY,NaN,UNKNOWN,NaN,NaN,UNKNOWN

In [7]:
!ls

drive  sample_data

In [8]:
df.head()

,bite_date,SpeciesIDDesc,BreedIDDesc,GenderIDDesc,color,vaccination_yrs,vaccination_date,victim_zip,AdvIssuedYNDesc,WhereBittenIDDesc,quarantine_date,DispositionIDDesc,head_sent_date,release_date,ResultsIDDesc
0,1985-05-05 00:00:00,DOG,NaN,FEMALE,LIG. BROWN,1.0,1985-06-20 00:00:00,40229,NO,BODY,1985-05-05 00:00:00,UNKNOWN,NaN,NaN,UNKNOWN
1,1986-02-12 00:00:00,DOG,NaN,UNKNOWN,BRO & BLA,NaN,NaN,40218,NO,BODY,1986-02-12 00:00:00,UNKNOWN,NaN,NaN,UNKNOWN
2,1987-05-07 00:00:00,DOG,NaN,UNKNOWN,NaN,NaN,NaN,40219,NO,BODY,1990-05-07 00:00:00,UNKNOWN,NaN,NaN,UNKNOWN
3,1988-10-02 00:00:00,DOG,NaN,MALE,BLA & BRO,NaN,NaN,NaN,NO,BODY,1990-10-02 00:00:00,UNKNOWN,NaN,NaN,UNKNOWN
4,1989-08-29 00:00:00,DOG,NaN,FEMALE,BLK-WHT,NaN,NaN,NaN,NO,BODY,NaN,UNKNOWN,NaN,NaN,UNKNOWN

In [15]:
df['bite_date'] = pd.to_datetime(df['bite_date'], errors='coerce')
df.dropna(subset=['bite_date'], inplace=True)
df['bite_year'] = df['bite_date'].dt.year

# Filter the DataFrame to include only years from 2010 to 2017
df_filtered_by_year = df[(df['bite_year'] >= 1985) & (df['bite_year'] <= 2017)].copy()

bites_per_year = df_filtered_by_year['bite_year'].value_counts().sort_index().reset_index()
bites_per_year.columns = ['year', 'num_bites']

fig = px.line(bites_per_year, x='year', y='num_bites',
              title='Number of Animal Bites Per Year (1985-2017)',
              labels={'year': 'Year', 'num_bites': 'Number of Bites'})
fig.update_xaxes(dtick="M1", tickformat="%Y", showgrid=True)
fig.update_yaxes(showgrid=True)
fig.show()

In [19]:
species_bites = df_filtered_by_year['SpeciesIDDesc'].value_counts().reset_index()
species_bites.columns = ['Species', 'Number of Bites']

# Filter to include only Dog, Cat, and Bat
species_bites_filtered = species_bites[species_bites['Species'].isin(['DOG', 'CAT', 'BAT'])]

fig_species = px.bar(species_bites_filtered, x='Species', y='Number of Bites',
                     title='Number of Animal Bites by Species (Dog, Cat, Bat) (1985-2017)',
                     labels={'Species': 'Animal Species', 'Number of Bites': 'Count'})
fig_species.update_xaxes(tickangle=45)
fig_species.show()

In [20]:
body_parts = df_filtered_by_year['WhereBittenIDDesc'].value_counts().reset_index()
body_parts.columns = ['Body Part', 'Number of Bites']

fig_pie = px.pie(body_parts, values='Number of Bites', names='Body Part',
                 title='Body Parts Most Frequently Bitten (1985-2017)')
fig_pie.show()